DROP TABLE IF EXISTS LOAN;
DROP TABLE IF EXISTS INCOME;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS HOUSEHOLD;


CREATE TABLE CLIENT (
    CUSTOMER_ID INT
    , REPORTING_DATE TEXT
    , EDUCATION TEXT NOT NULL
    , AGE INT NOT NULL
    , BUCKET INT NOT NULL
    , CHECK (CUSTOMER_ID > 0 AND BUCKET > 0)
    , CHECK (AGE BETWEEN 18 AND 100)
    , CHECK ((EDUCATION IN ("Secondary","Elementary","Higher Education")))
    , PRIMARY KEY(CUSTOMER_ID, REPORTING_DATE)
);


CREATE TABLE LOAN (
    LOAN_ID INT
    , CUSTOMER_ID INT
    , REPORTING_DATE TEXT NOT NULL
    , INTODEFAULT TEXT NOT NULL
    , INSTALLMENT_NM INT NOT NULL
    , LOAN_AMT NUMERIC NOT NULL
    , INSTALLMENT_AMT NUMERIC NOT NULL
    , PAST_DUE_AMT NUMERIC NOT NULL
    , BUCKET INT  NOT NULL
    , FOREIGN KEY(CUSTOMER_ID,REPORTING_DATE) REFERENCES CLIENT(CUSTOMER_ID,REPORTING_DATE) ON DELETE CASCADE
    , CHECK (LOAN_ID > 0 AND BUCKET > 0)
    , CHECK (LOAN_AMT BETWEEN 500 AND 100000)
    , CHECK (PAST_DUE_AMT >=0)
    , CHECK (INSTALLMENT_NM BETWEEN 12 AND 72)
    , CHECK (INTODEFAULT IN ("Y","N"))
    , PRIMARY KEY (LOAN_ID, REPORTING_DATE)
);

CREATE TABLE INCOME (
    INCOME_ID int
    , CUSTOMER_ID INT NOT NULL
    , REPORTING_DATE TEXT
    , FIRST_JOB TEXT(1) NOT NULL
    , INCOME INT NOT NULL
    , BUCKET INT NOT NULL
    , FOREIGN KEY(CUSTOMER_ID,REPORTING_DATE) REFERENCES CLIENT(CUSTOMER_ID,REPORTING_DATE) ON DELETE CASCADE
    , CHECK (FIRST_JOB IN ("Y","N"))
    , CHECK (CUSTOMER_ID > 0 AND INCOME_ID > 0 AND BUCKET > 0)
    , CHECK (INCOME BETWEEN 1000 AND 30000)
    , PRIMARY KEY (INCOME_ID,REPORTING_DATE)
);

CREATE TABLE HOUSEHOLD (
    HOUSEHOLD_ID INT
    , INCOME_ID INT NOT NULL
    , REPORTING_DATE TEXT NOT NULL
    , MARRIED TEXT NOT NULL
    , HOUSE_OWNER TEXT NOT NULL
    , BUCKET INT NOT NULL
    , CHILD_NO INT NOT NULL
    , HH_MEMBERS INT NOT NULL
    , FOREIGN KEY(INCOME_ID, REPORTING_DATE) REFERENCES INCOME(INCOME_ID, REPORTING_DATE) ON DELETE CASCADE
    , CHECK (HOUSEHOLD_ID > 0 AND BUCKET>0)
    , CHECK (CHILD_NO BETWEEN 0 AND 10)
    , CHECK (HH_MEMBERS BETWEEN 1 AND 10)
    , CHECK (MARRIED IN ("Y","N") AND HOUSE_OWNER IN ("Y","N"))
    , PRIMARY KEY (HOUSEHOLD_ID, REPORTING_DATE)
);



DROP TABLE IF EXISTS CUSTOMER_CAR;
CREATE TABLE CUSTOMER_CAR (
    CUSTOMER_ID INT 
    , REPORTING_DATE TEXT NOT NULL
    , EDUCATION TEXT NOT NULL
    , AGE FIRST JOB NOT NULL
    , BUCKET INT NOT NULL
    , LOAN_ID INT NOT NULL
    , INTODEFAULT INT NOT NULL
    , INSTALLMENT_NM INT NOT NULL
    , LOAN_AMT NUMERIC NOT NULL
    , INSTALLMENT_AMT NUMERIC NOT NULL
    , PAST_DUE_AMT NUMERIC NOT NULL
    , INCOME_ID INT NOT NULL
    , FIRST_JOB TEXT NOT NULL
    , INCOME INT NOT NULL
    , HOUSEHOLD_ID INT NOT NULL
    , MARRIED TEXT NOT NULL
    , HOUSE_OWNER TEXT NOT NULL
    , CHILD_NO INT NOT NULL
    , HH_MEMBERS INT NOT NULL
    , PRIMARY KEY (CUSTOMER_ID, INCOME_ID, LOAN_ID, HOUSEHOLD_ID, REPORTING_DATE)
    , FOREIGN KEY(CUSTOMER_ID, REPORTING_DATE) REFERENCES CLIENT(CUSTOMER_ID,REPORTING_DATE) ON DELETE CASCADE
    , FOREIGN KEY(INCOME_ID, REPORTING_DATE) REFERENCES INCOME(INCOME_ID,REPORTING_DATE) ON DELETE CASCADE
    , FOREIGN KEY(HOUSEHOLD_ID, REPORTING_DATE) REFERENCES HOUSEHOLD(HOUSEHOLD_ID,REPORTING_DATE) ON DELETE CASCADE
    , FOREIGN KEY(LOAN_ID, REPORTING_DATE) REFERENCES LOAN(LOAN_ID,REPORTING_DATE) ON DELETE CASCADE
);

---------------------------------------------------------------------------------------
------------------------------------- RAW TABLES --------------------------------------
---------------------------------------------------------------------------------------


DROP TABLE IF EXISTS RAW_CLIENT;
CREATE TABLE RAW_CLIENT
(
    CUSTOMER_ID TEXT
    , REPORTING_DATE TEXT
    , EDUCATION TEXT
    , AGE TEXT
    , BUCKET TEXT
);


DROP TABLE IF EXISTS RAW_INCOME;
CREATE TABLE RAW_INCOME
(
  INCOME_ID int
    , CUSTOMER_ID TEXT
    , REPORTING_DATE TEXT
    , FIRST_JOB TEXT
    , INCOME TEXT
    , BUCKET TEXT
);

DROP TABLE IF EXISTS RAW_HOUSEHOLD;
CREATE TABLE RAW_HOUSEHOLD
(
  HOUSEHOLD_ID TEXT
    , INCOME_ID TEXT
    , REPORTING_DATE TEXT
    , MARRIED TEXT
    , HOUSE_OWNER TEXT
    , BUCKET TEXT
    , CHILD_NO TEXT
    , HH_MEMBERS TEXT
);

DROP TABLE IF EXISTS RAW_LOAN;
CREATE TABLE RAW_LOAN
(
    LOAN_ID TEXT
    , CUSTOMER_ID TEXT
    , REPORTING_DATE TEXT
    , INTODEFAULT TEXT
    , INSTALLMENT_NM TEXT
    , LOAN_AMT NUMERIC TEXT
    , INSTALLMENT_AMT TEXT
    , PAST_DUE_AMT TEXT
    , BUCKET TEXT
)
