INSERT INTO CUSTOMER_CAR
SELECT AA.*
FROM (
SELECT
A.CUSTOMER_ID
,A.REPORTING_DATE
,A.EDUCATION
,A.AGE
,A.BUCKET
,B.LOAN_ID
,B.INTODEFAULT
,B.INSTALLMENT_NM
,B.LOAN_AMT
,B.INSTALLMENT_AMT
,B.PAST_DUE_AMT
,C.INCOME_ID
,C.FIRST_JOB
,C.INCOME
,D.HOUSEHOLD_ID
,D.MARRIED
,D.HOUSE_OWNER
,D.CHILD_NO
,D.HH_MEMBERS
FROM CLIENT A
INNER JOIN LOAN B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
    AND A.REPORTING_DATE = B.REPORTING_DATE
INNER JOIN INCOME C
    ON A.CUSTOMER_ID = C.CUSTOMER_ID
    AND A.REPORTING_DATE = C.REPORTING_DATE
INNER JOIN HOUSEHOLD D
    ON C.INCOME_ID = D.INCOME_ID
    AND C.REPORTING_DATE = D.REPORTING_DATE
) AA
    LEFT JOIN CUSTOMER_CAR BB ON
        AA.CUSTOMER_ID = BB.CUSTOMER_ID
        AND AA.INCOME_ID = BB.INCOME_ID
        AND AA.LOAN_ID = BB.LOAN_ID
        AND AA.HOUSEHOLD_ID = BB.HOUSEHOLD_ID
        AND AA.REPORTING_DATE = BB.REPORTING_DATE
WHERE BB.CUSTOMER_ID IS NULL;






--DASHBOARD REPORT
DROP VIEW IF EXISTS SUMMARY_RPT;
CREATE VIEW SUMMARY_RPT
AS
WITH DATE_BUCKET AS (
    SELECT DISTINCT REPORTING_DATE,
    BUCKET 
    FROM CUSTOMER_CAR
)

SELECT B.REPORTING_DATE
, A.SUM_PAID_AMOUNT
, A.SUM_LOAN
, A.PAST_DUE_SUM
FROM (
SELECT BUCKET, SUM(INSTALLMENT_AMT*BUCKET) SUM_PAID_AMOUNT
, SUM(LOAN_AMT) SUM_LOAN
, SUM(PAST_DUE_AMT) PAST_DUE_SUM
FROM CUSTOMER_CAR A
WHERE BUCKET > ((SELECT MAX(BUCKET) FROM CUSTOMER_CAR) - 3)
GROUP BY BUCKET
) A
    JOIN DATE_BUCKET B
    ON A.BUCKET = B.BUCKET;
    

--DPD BUCKET REPORT
DROP VIEW IF EXISTS DPD_RPT;
CREATE VIEW DPD_RPT
AS
WITH DATA_PREP AS(
    SELECT CUSTOMER_ID
    , REPORTING_DATE
    , PAST_DUE_AMT
    , PREVIOUS_PAST_DUE_AMT
    , INTODEFAULT
    , BUCKET
    , CASE WHEN PAST_DUE_AMT > 100 AND PREVIOUS_PAST_DUE_AMT > 100 THEN DAYS_REPORTING_DATE
        WHEN PAST_DUE_AMT > 100 THEN 1
        ELSE 0 END DAYS_TO_ADD
    FROM (
        SELECT A.*
        , strftime('%d',REPORTING_DATE) DAYS_REPORTING_DATE
        , LAG(PAST_DUE_AMT,1,0) OVER (PARTITION BY CUSTOMER_ID ORDER BY BUCKET) PREVIOUS_PAST_DUE_AMT
        FROM CUSTOMER_CAR A
    ) AA
)

SELECT D.DPD,D.REPORTING_DATE,
SUM(D.PAST_DUE_AMT) SUM_AMOUNT
FROM (
    SELECT C.*
    ,CASE WHEN CHECK_VALUE > 90 THEN 'DPD90+'
        WHEN CHECK_VALUE > 60 THEN 'DPD60+'
        WHEN CHECK_VALUE > 30 THEN 'DPD30+'
        WHEN CHECK_VALUE >= 1 THEN 'DPD30' 
        ELSE 'NONE' END DPD
    FROM (
        SELECT B.*
        , SUM(BUCKET_DAY) OVER (PARTITION BY CUSTOMER_ID ORDER BY REPORTING_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) CHECK_VALUE
        FROM (
            SELECT A.*
            ,CASE WHEN PAST_DUE_AMT > 100 AND  PREVIOUS_PAST_DUE_AMT > 100 THEN DAYS_TO_ADD
                WHEN PAST_DUE_AMT <= 100 AND PREVIOUS_PAST_DUE_AMT > 100 THEN SUM(DAYS_TO_ADD) OVER (PARTITION BY CUSTOMER_ID ORDER BY REPORTING_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)*(-1)
                WHEN PAST_DUE_AMT > 100 THEN 1
                ELSE 0 END BUCKET_DAY
            FROM DATA_PREP A
        ) B
    ) C
) D
    WHERE BUCKET > (SELECT MAX(BUCKET) FROM CUSTOMER_CAR) - 12
    AND DPD IN ('DPD30+','DPD60+','DPD90+')
    GROUP BY D.REPORTING_DATE, D.DPD;
        
    
