INSERT ALL
INTO players_data ('Diego Costa', 'Diego', 'da Silva Costa', 35, '39', '39')
INTO players_data ('Lucas Moura', 'Lucas', 'Rodrigues Moura da Silva', 31, '47', '39')
INTO players_data ('A. Oxlade-Chamberlain', 'Alexander Mark David', 'Oxlade-Chamberlain', 30, '40', '39')
INTO players_data ('P. Jones', 'Phil Anthony', 'Jones', 31, '33', '39')
INTO players_data ('J. Lingard', 'Jesse Ellis', 'Lingard', 31, '65', '39')
INTO players_data ('M. Lanzini', 'Manuel', 'Lanzini', 30, '48', '39')
INTO players_data ('João Moutinho', 'João Filipe', 'Iria Santos Moutinho', 37, '39', '39')
INTO players_data ('Adama Traoré', 'Adama', 'Traoré Diarra', 27, '39, 36', '39')
INTO players_data ('T. Davies', 'Thomas', 'Davies', 25, '45, 62', '39')
INTO players_data ('J. McArthur', 'James', 'McFarlane McArthur', 36, '52', '39')
INTO players_data ('L. Milivojević', 'Luka', 'Milivojević', 32, '52', '39')
INTO players_data ('A. Townsend', 'Andros Darryl', 'Townsend', 32, '45, 1359', '39')
INTO players_data ('A. Begović', 'Asmir', 'Begović', 36, '45', '39')
INTO players_data ('J. Stanislas', 'Felix Junior', 'Stanislas', 34, '35', '39')
INTO players_data ('C. Clark', 'Ciaran', 'Clark', 34, '62', '39')
INTO players_data ('J. Steer', 'Jed John', 'Steer', 31, '66', '39')
INTO players_data ('J. Colback', 'Jack Raymond', 'Colback', 34, '65', '39')
INTO players_data ('L. Taylor', 'Lyle James Alfred', 'Taylor', 33, '65', '39')
INTO players_data ('M. Longstaff', 'Matthew Ben', 'Longstaff', 23, '34', '39')
INTO players_data ('E. Wady', 'Ethan James', 'Wady', 21, '49', '39')
INTO players_data ('Wesley Moraes', 'Wesley', 'Moraes Ferreira da Silva', 27, '66', '39')
INTO players_data ('K. Hoever', 'Ki-Jana Delano', 'Hoever', 21, '39', '39')
INTO players_data ('Alex Telles', 'Alex', 'Nicolao Telles', 31, '33', '39')
INTO players_data ('David de Gea', 'David', 'de Gea Quintana', 33, '33', '39')
INTO players_data ('M. Sanson', 'Morgan Stéphane', 'Sanson', 29, '66', '39')
INTO players_data ('R. Giles', 'Ryan John', 'Giles', 23, '39, 1359', '39')
INTO players_data ('R. Laryea', 'Richmond Mamah', 'Laryea', 28, '65', '39')
INTO players_data ('J. Bowler', 'Joshua Luke', 'Bowler', 24, '65', '39')
INTO players_data ('A. Pressley', 'Aaron Alex', 'Pressley', 22, '55', '39')
INTO players_data ('I. Kaboré', 'Issa', 'Kaboré', 22, '50, 1359', '39')
INTO players_data ('W. Fish', 'William Thomas', 'Fish', 20, '33', '39')
INTO players_data ('M. Bidstrup', 'Mads', 'Bidstrup', 22, '55', '39')
INTO players_data ('Yan Couto', 'Yan', 'Bueno Couto', 21, '50', '39')
INTO players_data ('I. Samuels', 'Imari-Narain', 'Che Hines-Samuels', 20, '51', '39')
INTO players_data ('C. Cîrjan', 'Cătălin Ionuț', 'Cîrjan', 21, '42', '39')
INTO players_data ('C. Rushworth', 'Carl Andrew', 'Rushworth', 22, '51', '39')
INTO players_data ('J. Wilson-Esbrand', 'Joshua Darius', 'Kamani Wilson-Esbrand', 21, '50', '39')
INTO players_data ('K. Edwards', 'Khayon', 'Edwards', 20, '42', '39')
INTO players_data ('F. Potts', 'Freddie', 'Potts', 20, '48', '39')
INTO players_data ('C. Patino', 'Charlie Michael', 'Patino', 20, '42', '39')
SELECT 1 FROM DUAL;