--Procedura tworzenia tabel powiązanych ze stanami aktualnymi/poprzednimi tabeli faktów wymiaru geograficznego
CREATE OR REPLACE PROCEDURE ADD_TAB(NAME_TAB VARCHAR2 DEFAULT NULL, NAME_TAB_DATABASE OUT VARCHAR2)
IS
    SQL_STAT VARCHAR2(10000);
    SYS_CHAR varchar2(100);
BEGIN
    SELECT TO_CHAR(EXTRACT(YEAR FROM SYSDATE)) || TO_CHAR(EXTRACT(MONTH FROM SYSDATE)) INTO SYS_CHAR
    FROM DUAL;

    IF NAME_TAB IS NULL THEN
        NAME_TAB_DATABASE:= 'COUNTRY_DICT_'||sys_char;
    ELSE
        NAME_TAB_DATABASE:= 'COUNTRY_DICT_'||name_tab;
    END IF;
    SQL_STAT := 'CREATE TABLE '||NAME_TAB_DATABASE||' (
    COUNTRY_CODE VARCHAR2(100),
    COUNTRY_REG VARCHAR2(4),
    START_DATE DATE DEFAULT SYSDATE,
    END_DATAE DATE DEFAULT NULL)';
    EXECUTE IMMEDIATE SQL_STAT;
END;

/
--przepisywanie stanu aktualnego jako poprzedniego z określoną datą/tworzenie tabeli dla stanów aktualnych
--blok oparty o założenie możliwości odwoływania się do stanów poprzednich/aktualnych oraz tworzenia stanów poprzednich nie częściej niż raz na dzień
--możliwośc modyfikacji procedury ADD_TAB o zmienną domyślną CURRENT_TIMESTAMP i wykonywanie funkcji raz na sekundę lub poszerzenie o funkcje usuwającą kolidująca tabelę
DECLARE
    SQL_STAT VARCHAR2(1000);
    TAB_NAME VARCHAR2(50);
    COUNTER SMALLINT;
BEGIN
    SELECT COUNT(*) INTO COUNTER FROM USER_TABLES WHERE TABLE_NAME = 'COUNTRY_DICT_ACT';
    
    IF COUNTER > 0 THEN 
        ADD_TAB(NULL,TAB_NAME);
        SQL_STAT := 'INSERT INTO '||TAB_NAME||' SELECT * FROM COUNTRY_DICT_ACT';
        EXECUTE IMMEDIATE SQL_STAT;
        BEGIN  
            FOR I IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('COUNTRY_DICT_ACT','TEMP_DATA'))
            LOOP
             EXECUTE IMMEDIATE 'TRUNCATE TABLE '||I.TABLE_NAME;
             EXECUTE IMMEDIATE 'DROP TABLE '||I.TABLE_NAME;
            END LOOP;
        END;
        SQL_STAT := 'CREATE GLOBAL TEMPORARY TABLE TEMP_DATA ON COMMIT PRESERVE ROWS AS SELECT * FROM '||TAB_NAME;
        EXECUTE IMMEDIATE SQL_STAT;
    END IF;
    ADD_TAB('ACT',TAB_NAME);
END;

/
--insert do tabeli z danymi aktualnymi stworzony w oparciu o modyfikacje regionów ręcznie w excelu
INSERT ALL
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Vietnam|VNM','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Argentina|ARG','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Australia|AUS','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Brazil|BRA','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Britain|GBR','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Canada|CAN','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Chile|CHL','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('China|CHN','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Colombia|COL','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Costa Rica|CRI','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Czech Republic|CZE','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Denmark|DNK','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Egypt|EGY','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Euro area|EUR','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Hong Kong|HKG','REG1')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Hungary|HUN','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('India|IND','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Indonesia|IDN','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Israel|ISR','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Japan|JPN','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Lithuania|LTU','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Malaysia|MYS','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Mexico|MEX','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('New Zealand|NZL','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Norway|NOR','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Pakistan|PAK','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Peru|PER','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Philippines|PHL','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Poland|POL','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Russia|RUS','REG2')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Saudi Arabia|SAU','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Singapore|SIN','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('South Africa|ZAF','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('South Korea|KOR','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Sri Lanka|LKA','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Sweden|SWE','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Switzerland|CHE','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Taiwan|ROC','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Thailand|THA','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Turkey|TUR','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('UAE|UAE','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Ukraine|UKR','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('United States|USA','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Uruguay|URY','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Venezuela|VEN','REG3')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Austria|AUT','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Belgium|BEL','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Estonia|EST','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Finland|FIN','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('France|FRA','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Germany|DEU','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Greece|GRC','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Ireland|IRL','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Italy|ITA','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Netherlands|NLD','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Portugal|PRT','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Spain|ESP','REG4')
    INTO COUNTRY_DICT_ACT(COUNTRY_CODE,COUNTRY_REG) VALUES('Latvia|LVA','REG4')
SELECT 1 FROM DUAL;

/

--sprawdzanie zmian pomiedzy tabelą old oraz act -> wprowadzenie aktualnej daty jako zakonczenie okresu przy zmianach -> wprowadzenie nowego rekordu obowiązującego od daty zmiany
DECLARE
	COL_NUMBER SMALLINT;
    SQL_STAT VARCHAR2(1000);
BEGIN
	SELECT COUNT(*) INTO COL_NUMBER FROM USER_TABLES WHERE TABLE_NAME = 'COUNTRY_DICT_FINAL';
	
	IF COL_NUMBER < 1 THEN
        SQL_STAT := 'CREATE TABLE COUNTRY_DICT_FINAL AS SELECT * FROM TEMP_DATA';
		EXECUTE IMMEDIATE SQL_STAT;
    END IF;
END;

/

BEGIN
	FOR I IN (SELECT A.COUNTRY_CODE,A.COUNTRY_REG
	FROM TEMP_DATA A
	LEFT JOIN COUNTRY_DICT_ACT B
		ON A.COUNTRY_CODE = B.COUNTRY_CODE AND A.COUNTRY_REG = B.COUNTRY_REG
	WHERE B.COUNTRY_CODE IS NULL
	)
	LOOP
		UPDATE COUNTRY_DICT_FINAL
		SET END_DATAE = SYSDATE
		WHERE COUNTRY_CODE = I.COUNTRY_CODE;
		INSERT INTO COUNTRY_DICT_FINAL(COUNTRY_CODE,COUNTRY_REG,START_DATE) VALUES(I.COUNTRY_CODE,I.COUNTRY_REG,SYSDATE);
	END LOOP;
END;



