CREATE GLOBAL TEMPORARY TABLE DANE_N_POPULACJA
ON COMMIT PRESERVE ROWS AS

With baza as (Select distinct Data_Danych, ID_TR_DEF, BFG
From ops$hurt.stany_zabezpieczen a
left join AM_Rodzaj_Zabezpieczen b on a.Rodzaj_opis = b.rodzaj_opis
where data_danych >= '01.01.2013')

,dane as ( SELECT A.*,
CASE WHEN INSTR(USUNIECIE,'#',-1,1) > 0 THEN SUBSTR(USUNIECIE,0,INSTR(USUNIECIE,'#',-1,1)-1)
    ELSE USUNIECIE END USUNIECIE_FINAL
FROM (
SELECT D.*,
CASE WHEN INSTR(teid,'_',-1,1) > 0 THEN SUBSTR(TEID,INSTR(teid,'_',-1,1)+1,LENGTH(TEID)) 
        ELSE TEID END AS USUNIECIE
FROM PS_DATA_FILAR_CALC202303 D
--where length(teid) > 9
) A
)

--WHERE LENGTH(USUNIECIE) > 7)

--,wyliczenie_DR as (
--    SELECT D.BUSINESSDATE,D.DEFFLAG,B.BFG,B.ID_TR_DEF,MAX(D2.DEFFLAG) AS DEF36
--    FROM BAZA B
--    INNER JOIN DANE D ON B.DATA_DANYCH = D.BUSINESSDATE AND B.ID_TR_DEF = TO_NUMBER(D.USUNIECIE_FINAL)
--    LEFT JOIN DANE D2 ON D.USUNIECIE_FINAL = D2.USUNIECIE_FINAL AND D2.BUSINESSDATE BETWEEN ADD_MONTHS(D.BUSINESSDATE,1) AND ADD_MONTHS(D.BUSINESSDATE,36)
--    GROUP BY D.BUSINESSDATE,D.DEFFLAG,B.BFG,B.ID_TR_DEF
--)
 SELECT D.BUSINESSDATE,D.DEFFLAG,B.BFG,B.ID_TR_DEF,MAX(D2.DEFFLAG) AS DEF36
    FROM BAZA B
    INNER JOIN DANE D ON B.DATA_DANYCH = D.BUSINESSDATE AND B.ID_TR_DEF = TO_NUMBER(D.USUNIECIE_FINAL)
    LEFT JOIN DANE D2 ON D.USUNIECIE_FINAL = D2.USUNIECIE_FINAL AND D2.BUSINESSDATE BETWEEN ADD_MONTHS(D.BUSINESSDATE,1) AND ADD_MONTHS(D.BUSINESSDATE,36)
    GROUP BY D.BUSINESSDATE,D.DEFFLAG,B.BFG,B.ID_TR_DEF;

SELECT * FROM DANE_N_POPULACJA
